### ISSUE TITLE
Add repository to packagist.org

### ISSUE THREAD

**Issue by giuseppemorelli** [aleron75-archive/Webgriffe_Maintenance#6]
Hi Ale,
please, can you add your repository to packagistorg?
Or maybe you have a new version of this extension?
So I can download with composer directly without add the repository in my json file.

Thank you!

**Comment by aleron75** [comment]
Hi Giuseppe,
thank you for the idea, just submitted to packagist!
Cheers

**Comment by giuseppemorelli** [comment]
Hi Alessandro,
please can you check if "aleron75/webgriffe-maintenance" is submitted correctly on packagist.org?
My composer give me "typo error" and I can't find it via packagist.org search engine.

Thank you very much!

**Comment by aleron75** [comment]
Hi Giuseppe,
I re-submitted the module on packagist.
